/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulasistasiunradio;

import javax.swing.JOptionPane;

/**
 *
 * @author fadhlan
 */
public class InterfaceLogin extends javax.swing.JFrame {
    private static String user = "eek goreng";
    private static String pass = "nikmat rasanya";

    /**
     * Creates new form InterfaceAwal
     */
    public InterfaceLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        about = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 26)); // NOI18N
        jLabel2.setText("PROGRAM SIMULASI STASIUN RADIO FM DI JAWA TIMUR");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 0, 720, 80);

        next.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        next.setText("NEXT");
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });
        jPanel1.add(next);
        next.setBounds(360, 320, 140, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simulasistasiunradio/lambang ITS1.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 0, 70, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simulasistasiunradio/lambang MTK1.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(820, 10, 60, 60);
        jPanel1.add(username);
        username.setBounds(320, 200, 220, 40);

        jLabel5.setText("Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(320, 240, 60, 14);

        jLabel6.setText("Username");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(320, 180, 60, 14);
        jPanel1.add(password);
        password.setBounds(320, 260, 220, 40);

        about.setText("About");
        jPanel1.add(about);
        about.setBounds(0, 0, 61, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simulasistasiunradio/O9FG4W0.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        if(user.equals(username.getText().toString()) && pass.equals(password.getText().toString())) {
            InterfaceMain baru = new InterfaceMain(user,null);
            baru.setVisible(true);
            this.setVisible(false);
        }
        else {
            new PopUp().show_error("Username atau Password salah","Failed");
        }
    }//GEN-LAST:event_nextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton next;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}