/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulasistasiunradio;

import java.util.ArrayList;

/**
 *
 * @author gdwyn
 */
public class InterfaceMain extends javax.swing.JFrame {
    private static int state = 0;
    public static Input Input = new Input();
    private static InterfaceMain a;
    private String user = "";
    private ArrayList<Koordinat> points = null;
    /**
     * Creates new form InterfaceMain
     */
    public InterfaceMain() {
        initComponents();
    }
    
    public InterfaceMain(String user,ArrayList<Koordinat> points) {
        initComponents();
        this.user = user;
        lbl_username.setText(this.user);
        if(points != null) {
            Input.clear();
            Input.points = points;
            Input.repaint();
            state = 2;
            setView();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = Input;
        lbl_username = new javax.swing.JLabel();
        btn_next = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Load = new javax.swing.JLabel();
        About = new javax.swing.JLabel();
        Foto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 26)); // NOI18N
        jLabel2.setText("PROGRAM SIMULASI STASIUN RADIO FM DI JAWA TIMUR");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 0, 720, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simulasistasiunradio/lambang ITS1.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 0, 70, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simulasistasiunradio/lambang MTK1.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(920, 10, 60, 60);

        jPanel2.setPreferredSize(new java.awt.Dimension(872, 491));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(120, 80, 870, 450);

        lbl_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_username.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_username.setText("Username");
        lbl_username.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(lbl_username);
        lbl_username.setBounds(0, 550, 120, 70);

        btn_next.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_next.setText("Next");
        btn_next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nextMouseClicked(evt);
            }
        });
        jPanel1.add(btn_next);
        btn_next.setBounds(860, 550, 130, 40);

        btn_clear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clearMouseClicked(evt);
            }
        });
        jPanel1.add(btn_clear);
        btn_clear.setBounds(400, 550, 130, 40);

        btn_back.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_back.setText("Back");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        jPanel1.add(btn_back);
        btn_back.setBounds(120, 550, 130, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30", "40", "50", "60" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(600, 550, 110, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Radius");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(550, 550, 40, 17);

        Home.setText("Home");
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        jPanel1.add(Home);
        Home.setBounds(0, 0, 90, 14);

        Load.setText("Load");
        Load.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoadMouseClicked(evt);
            }
        });
        jPanel1.add(Load);
        Load.setBounds(0, 20, 80, 14);

        About.setText("About");
        About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutMouseClicked(evt);
            }
        });
        jPanel1.add(About);
        About.setBounds(0, 40, 90, 14);

        Foto.setText("Foto");
        jPanel1.add(Foto);
        Foto.setBounds(0, 530, 70, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simulasistasiunradio/O9FG4W0.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1100, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setView() {
        Input.maxColor = 0;
        if(state == 0) {
            btn_next.setVisible(true);
            btn_back.setVisible(false);
            btn_clear.setVisible(true);
            jComboBox1.setVisible(true);
            jLabel5.setVisible(true);
            Input.enable = true;
            Load.setVisible(true);
        }
        else if(state == 1) {
            this.points = Input.points;
            btn_next.setVisible(true);
            btn_back.setVisible(true);
            btn_clear.setVisible(false);
            jComboBox1.setVisible(false);
            jLabel5.setVisible(false);
            Input.enable = false;
            Load.setVisible(false);
        }
        else if(state == 2){
            btn_next.setVisible(true);
            btn_back.setVisible(true);
            btn_clear.setVisible(false);
            jComboBox1.setVisible(false);
            jLabel5.setVisible(false);
            Input.enable = false;
            Load.setVisible(false);
        }
    }  
    
    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
        state--;
        setView();
        Input.state--;
        Input.repaint();
        jPanel1 = Input;
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseClicked
        // TODO add your handling code here:
        int dialog = new PopUp().show_yesno("pesan", "judul");
        if(dialog == 0) {
            Input.clear();
            Input.repaint();
            jPanel1 = Input;
        }
    }//GEN-LAST:event_btn_clearMouseClicked

    private void btn_nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nextMouseClicked
        // TODO add your handling code here:
        if(state == 3) {
            InterfaceKesimpulan baru = new InterfaceKesimpulan(this);
            baru.setVisible(true);
            this.setVisible(false);
        }
        else {
            state++;
            setView();
            Input.state++;
            if(state == 1) Input.cariTabrakan();
            else Input.print();
            Input.repaint();
            jPanel1 = Input;
        }
    }//GEN-LAST:event_btn_nextMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:
        int dialog = new PopUp().show_yesno("pesan", "judul");
        if(dialog == 0) {
            InterfaceLogin baru = new InterfaceLogin();
            baru.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_HomeMouseClicked
    
    private void LoadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoadMouseClicked
        // TODO add your handling code here:
        new DataFile().load(this);
    }//GEN-LAST:event_LoadMouseClicked

    private void AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                a = new InterfaceMain();
                a.setVisible(true);
                a.setResizable(false);
                Input.enable = true;
                new Thread(new CekRadius(jComboBox1,Input)).start();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel About;
    private javax.swing.JLabel Foto;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Load;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_next;
    private static javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_username;
    // End of variables declaration//GEN-END:variables
}
